# Generated by Django 4.2.28 on 2026-03-24 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="discussionroom",
            name="moderators",
        ),
        migrations.AlterField(
            model_name="discussionroom",
            name="access_type",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("club_only", "Club only"),
                    ("event_only", "Event only"),
                    ("private_invite_only", "Private invite only"),
                ],
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("in_review", "In review"),
                    ("dismissed", "Dismissed"),
                    ("action_taken", "Action taken"),
                ],
                default="open",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="RoomInvite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("revoked", "Revoked"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invited_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_room_invites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_invites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invites",
                        to="rooms.discussionroom",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="roominvite",
            constraint=models.UniqueConstraint(
                fields=("room", "recipient"), name="unique_room_invite"
            ),
        ),
    ]
