# Generated by Django 4.2.28 on 2026-03-25 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_remove_discussionroom_moderators_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomhandle',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('left', 'Left'), ('expelled', 'Expelled')], max_length=16),
        ),
    ]
