# Generated by Django 4.2.28 on 2026-03-25 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_roomhandle_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussionroom',
            name='access_type',
            field=models.CharField(choices=[('public', 'Public'), ('club_only', 'Club only'), ('event_only', 'Event only'), ('private_invite_only', 'Private (invite only)')], max_length=25),
        ),
        migrations.AlterField(
            model_name='discussionroom',
            name='room_type',
            field=models.CharField(choices=[('club', 'Club'), ('event', 'Event'), ('topic', 'Open room')], max_length=10),
        ),
    ]
