# Generated by Django 4.2.28 on 2026-03-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlogentry",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("club_created", "Club created"),
                    ("club_updated", "Club updated"),
                    ("club_joined", "Club joined"),
                    ("club_left", "Club left"),
                    ("club_member_removed", "Club member removed"),
                    ("role_granted", "Role granted"),
                    ("role_revoked", "Role revoked"),
                    ("event_created", "Event created"),
                    ("event_updated", "Event updated"),
                    ("event_cancelled", "Event cancelled"),
                    ("event_archived", "Event archived"),
                    ("room_created", "Room created"),
                    ("room_updated", "Room updated"),
                    ("room_archived", "Room archived"),
                    ("room_invite_created", "Room invite created"),
                    ("room_invite_updated", "Room invite updated"),
                    ("announcement_created", "Announcement created"),
                    ("report_dismissed", "Report dismissed"),
                    ("message_deleted", "Message deleted"),
                    ("handle_muted", "Handle muted"),
                    ("handle_expelled", "Handle expelled"),
                    ("handle_revealed", "Handle revealed"),
                    ("delete_and_mute", "Delete and mute"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("event_registered", "Event registered"),
                    ("waitlisted", "Waitlisted"),
                    ("waitlist_promoted", "Waitlist promoted"),
                    ("event_updated", "Event updated"),
                    ("event_cancelled", "Event cancelled"),
                    ("moderation_action", "Moderation action"),
                    ("announcement", "Announcement"),
                    ("invite", "Invite"),
                    ("generic", "Generic"),
                ],
                default="generic",
                max_length=32,
            ),
        ),
    ]
