# Generated by Django 4.2.28 on 2026-03-24 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emailotpchallenge'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailotpchallenge',
            new_name='accounts_em_email_f4c534_idx',
            old_name='accounts_otp_email_created',
        ),
    ]
