# Generated by Django 4.2.28 on 2026-03-24 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_accounts_otp_email_created_accounts_em_email_f4c534_idx'),
        ('accounts', '0003_user_email_verification_fields'),
    ]

    operations = [
    ]
