# Generated by Django 4.2.28 on 2026-03-24 16:39

from django.db import migrations, models


def migrate_legacy_roles(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.filter(role__in=["club_rep", "moderator"]).update(role="student")


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_merge_20260324_2026"),
    ]

    operations = [
        migrations.RunPython(migrate_legacy_roles, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("institute_admin", "Institute Admin"),
                    ("system_admin", "System Admin"),
                ],
                default="student",
                max_length=32,
            ),
        ),
    ]
