# Generated by Django 4.2.28 on 2026-03-24 16:39

from django.conf import settings
from django.db import migrations, models


def migrate_memberships(apps, schema_editor):
    Club = apps.get_model("clubs_events", "Club")
    ClubFollow = apps.get_model("clubs_events", "ClubFollow")
    ClubMembership = apps.get_model("clubs_events", "ClubMembership")

    for club in Club.objects.all():
        for user in club.representatives.all():
            ClubMembership.objects.update_or_create(
                club=club,
                user=user,
                defaults={"status": "active", "local_role": "coordinator"},
            )

    for follow in ClubFollow.objects.select_related("club", "user"):
        ClubMembership.objects.update_or_create(
            club=follow.club,
            user=follow.user,
            defaults={"status": "active", "local_role": "member"},
        )

import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rooms", "0002_remove_discussionroom_moderators_and_more"),
        ("clubs_events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="ClubMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("left", "Left"), ("removed", "Removed")],
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "local_role",
                    models.CharField(
                        choices=[("member", "Member"), ("secretary", "Club Secretary"), ("coordinator", "Club Coordinator")],
                        default="member",
                        max_length=16,
                    ),
                ),
                ("joined_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("assigned_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="assigned_memberships", to=settings.AUTH_USER_MODEL)),
                ("club", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="memberships", to="clubs_events.club")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="club_memberships", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-joined_at"]},
        ),
        migrations.CreateModel(
            name="Announcement",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("target_type", models.CharField(choices=[("club", "Club"), ("event", "Event"), ("room", "Room")], max_length=8)),
                ("title", models.CharField(max_length=120)),
                ("body", models.TextField(max_length=1200)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("author", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="announcements", to=settings.AUTH_USER_MODEL)),
                ("club", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="announcements", to="clubs_events.club")),
                ("event", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="announcements", to="clubs_events.event")),
                ("room", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="announcements", to="rooms.discussionroom")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.RunPython(migrate_memberships, migrations.RunPython.noop),
        migrations.RemoveField(model_name="club", name="followers"),
        migrations.RemoveField(model_name="club", name="representatives"),
        migrations.AddConstraint(model_name="clubmembership", constraint=models.UniqueConstraint(fields=("club", "user"), name="unique_club_membership")),
    ]
